### ISSUE TITLE
Exception thrown while throwing an exception obscures validation errors

### ISSUE THREAD

**Issue by nhaynes** [DevCycleHQ/php-server-sdk#17]
The SDK has an issue when raising exceptions for invalid data.

For instance if you make a call to `allVariables` and omit `user_id`, you would expect to receive an `InvalidArgumentException` with the message `"User data is invalid: 'user_id' can't be null"` but instead you recieve:

 `ErrorException: Array to string conversion in /var/www/html/vendor/devcycle/php-server-sdk/lib/Api/DVCClient.php:139`

This is because the actual throwing of the exception has a bug, it's attempting to use string interpolation with an array:

`throw new \InvalidArgumentException("User data is invalid: $errors");`

This programming practice seems to be used in a few places, for instance on DVCClient:157.

This leaves the consumer of the SDK in a situation where it gets a rather cryptic exception instead of the helpful validation messages that were intended.

**Comment by kaushalkapasi** [comment]
Hey @nhaynes, thanks for bringing this to our attention! We'll get this addressed shortly!
